-- MySQL Script generated by MySQL Workbench
-- Fri Nov 28 15:59:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Seguradoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguradoras` (
  `id_Seguradora` INT NOT NULL AUTO_INCREMENT,
  `nome_seguradora` VARCHAR(100) NOT NULL,
  `cnpj_seguradora` VARCHAR(20) NOT NULL,
  `endereco_seguradora` VARCHAR(200) NOT NULL,
  `contato_seguradora` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Seguradora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Beneficiários`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Beneficiários` (
  `id_Beneficiario` INT NOT NULL AUTO_INCREMENT,
  `nome_razao_social` VARCHAR(100) NOT NULL,
  `cpf_cnpj` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `contato` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Beneficiario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tomadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tomadores` (
  `id_Tomador` INT NOT NULL AUTO_INCREMENT,
  `nome_razao_social` VARCHAR(100) NOT NULL,
  `cpf_cnpj` VARCHAR(20) NOT NULL,
  `endereco` VARCHAR(200) NOT NULL,
  `contato_tomadores` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Tomador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguros` (
  `id_Seguros` INT NOT NULL,
  `tipo_do_seguro` VARCHAR(50) NOT NULL,
  `valor_garantido` DECIMAL(15,2) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `Seguradoras_id_Seguradora` INT NOT NULL,
  `Tomadores_id_Tomador` INT NOT NULL,
  PRIMARY KEY (`id_Seguros`, `Seguradoras_id_Seguradora`, `Tomadores_id_Tomador`),
  INDEX `fk_Seguros_Seguradoras_idx` (`Seguradoras_id_Seguradora` ASC) VISIBLE,
  INDEX `fk_Seguros_Tomadores1_idx` (`Tomadores_id_Tomador` ASC) VISIBLE,
  CONSTRAINT `fk_Seguros_Seguradoras`
    FOREIGN KEY (`Seguradoras_id_Seguradora`)
    REFERENCES `mydb`.`Seguradoras` (`id_Seguradora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Seguros_Tomadores1`
    FOREIGN KEY (`Tomadores_id_Tomador`)
    REFERENCES `mydb`.`Tomadores` (`id_Tomador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contratos Vinculados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contratos Vinculados` (
  `id_Contratos` INT NOT NULL AUTO_INCREMENT,
  `objeto_contrato` VARCHAR(100) NOT NULL,
  `valor_contrato` DECIMAL(15,2) NOT NULL,
  `prazo_execucao` DATE NOT NULL,
  `Seguros_id_Seguros` INT NOT NULL,
  PRIMARY KEY (`id_Contratos`, `Seguros_id_Seguros`),
  INDEX `fk_Contratos Vinculados_Seguros1_idx` (`Seguros_id_Seguros` ASC) VISIBLE,
  CONSTRAINT `fk_Contratos Vinculados_Seguros1`
    FOREIGN KEY (`Seguros_id_Seguros`)
    REFERENCES `mydb`.`Seguros` (`id_Seguros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguro Beneficiarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguro Beneficiarios` (
  `Beneficiários_id_Beneficiario` INT NOT NULL,
  `Seguros_id_Seguros` INT NOT NULL,
  PRIMARY KEY (`Beneficiários_id_Beneficiario`, `Seguros_id_Seguros`),
  INDEX `fk_Beneficiários_has_Seguros_Seguros1_idx` (`Seguros_id_Seguros` ASC) VISIBLE,
  INDEX `fk_Beneficiários_has_Seguros_Beneficiários1_idx` (`Beneficiários_id_Beneficiario` ASC) VISIBLE,
  CONSTRAINT `fk_Beneficiários_has_Seguros_Beneficiários1`
    FOREIGN KEY (`Beneficiários_id_Beneficiario`)
    REFERENCES `mydb`.`Beneficiários` (`id_Beneficiario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Beneficiários_has_Seguros_Seguros1`
    FOREIGN KEY (`Seguros_id_Seguros`)
    REFERENCES `mydb`.`Seguros` (`id_Seguros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
